Provides plugins for both builders and improves params configuration.
maliput/maliput_multilane pull request #99
Opened 2022-12-20 14:55 UTC by francocipollone

# 🎉 New feature

Related to https://github.com/maliput/maliput_documentation/issues/124

## Summary

### Context
- `maliput_multilane` has two builders that are embedded together within the RoadNetworkLoader plugin. This is not ideal given that both corresponds to different kind of parameters.
- The documentation of the parameters could be improved

This PR:
 - Creates a separate RoadNetworkLoader plugin for using the OnRamp builder.
 - Improve documentation regarding the parameters that can be passed to the builders.

## Bonus

[maliput_viz] An example of dealing with both plugins:

https://user-images.githubusercontent.com/53065142/208694289-4a3e7edd-3a65-4215-bb56-c1165d4fd6b6.mp4

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

2022-12-21 17:10 UTC, agalbachicar requested changes
PTAL.

2022-12-21 17:10 UTC, agalbachicar commented on src/maliput_multilane/road_network_builder.cc
> +}
```suggestion
std::map<std::string, std::string> RoadNetworkConfiguration::ToStringMap() const {
  return {{params::kYamlFile, yaml_file}, {params::kYamlDescription, yaml_description}};
}
```

2022-12-21 20:25 UTC, francocipollone commented on src/plugin/on_ramp_road_network.cc
> +#include <memory>
Done.

2022-12-21 20:25 UTC, francocipollone commented on include/maliput_multilane/road_network_builder.h
> +  std::map<std::string, std::string> ToStringMap() const;
Done.

2022-12-21 20:25 UTC, francocipollone commented on include/maliput_multilane/multilane_onramp_merge.h
> +  std::map<std::string, std::string> ToStringMap() const;
Done.

2022-12-22 12:51 UTC, agalbachicar approved these changes
LGTM

2022-12-22 14:09 UTC, merged